### ISSUE TITLE
Not receiving notifications while app is in foreground

### ISSUE THREAD

**Issue by JuanPabloBoero** [smilefam/sendbird-ios-framework#11]
I am using SendBirdSDK 3.0.17, iOS 9.3, swift 2.3.

While chatting with some user, that user receives push notifications if the user app is not active, but once the app is active  `didReceiveRemoteNotification` wont get fired by new messages, i even enabled debug mode, in the console i can see that the message is received, but never gets to the AppDelegate method, is this a desired behaviour? are you intercepting remote notifications before reaching the method? thanks.

**Comment by sf-jed-kyung** [comment]
The behavior is intended by us. The push notification is sent to the offline user by SendBird push server. SendBirdSDK becomes offline automatically when the app is switched to background. I think that you don’t have to receive the push notification for all messages. If the app is online, every message is received on [`– channel:didReceiveMessage:`](https://docs.sendbird.com/ref/ios/Protocols/SBDChannelDelegate.html#//api/name/channel:didReceiveMessage:) delegate. I recommend that the local notification for the message should be implemented in the delegate.

**Comment by JuanPabloBoero** [comment]
Ok, i implemented `channel(sender: SBDBaseChannel, didReceiveMessage message: SBDBaseMessage)` in my `AppDelegate`, and `SBDMain.addChannelDelegate(self, identifier: self.description)` and the delegate started receiving the messages, now i fire a `NSNotification` in order to execute my logic. thanks!

**Comment by karuppasamypandian0856** [comment]
Push notification not received.Please help me out!
