### ISSUE TITLE
didSucceedReconnection, didFailReconnection not call

### ISSUE THREAD

**Issue by jacks8x** [smilefam/sendbird-ios-framework#12]
After comeback app from background, didSucceedReconnection or didFailReconnection are not called.
Just method didStartReconnection() is called

**Comment by sf-jed-kyung** [comment]
Hi,

We recognized the problem and the fixed SDK will be released next week. 

Thanks.

**Comment by sf-jed-kyung** [comment]
https://github.com/smilefam/SendBird-iOS/issues/16

**Comment by sf-jed-kyung** [comment]
https://github.com/smilefam/SendBird-iOS/issues/16

**Comment by sf-jed-kyung** [comment]
We fixed it in v3.0.19. Please try it. Thanks.
