### ISSUE TITLE
iOS: try to connect with user got this issue

### ISSUE THREAD

**Issue by karuppasamypandian0856** [smilefam/sendbird-ios-framework#13]
Just added SDK manually and added this line to Xcode -> Build Settings -> Linking -> Other Linker Flags.

-ObjC -l"icucore" -framework "CFNetwork" -framework "Foundation" -framework "MobileCoreServices" -framework "QuartzCore" -framework "Security" -framework "UIKit" -framework "CoreGraphics"

```
    [SBDMain initWithApplicationId:@"----------------------xxxxxxxx"];

    [SBDMain connectWithUserId:USER_ID accessToken:ACCESS_TOKEN completionHandler:^(SBDUser * _Nullable user, SBDError * _Nullable error) {
        // ...
        if (error != nil) {
            NSLog(@"NO ERROR FOUND %@",user);
        }
        else
        {
            NSLog(@"ERROR FOUND in connecting user %@",error.description);
        }
    }];
```
**Got this log**
Time diff of routing: 2.517095
[SendBird] Routing: https://api.sendbird.com : wss://ws.s
[SendBird] Start getHostUrlWithCompletionhandler: 1484732
[SendBird] Finish getHostUrlWithCompletionhandler: 148473
[SendBird] URL: https://api.sendbird.comhttps://api.sendb
[SendBird] Finish HTTP session: 1484732636.786725 CFNetwork SSLHandshake failed (-9807)
SendBird] Stop Pinger.
SendBird] Stop Watchdog.
SendBird] WS Error. Error Domain=NSOSStatusErrorDomain ComErrorDomainKey=3}
SendBird] Set reconnect timer: 0.000000, count: 1
SendBird] Stop Pinger.
SendBird] Stop Watchdog.
SendBird] ReconnectTimer timeout. Try to reconnect...
SendBird] Stop Pinger.
SendBird] Stop Watchdog.
SendBird] Reconnect start.CFNetwork SSLHandshake failed (-9807)

**Comment by sf-jed-kyung** [comment]
Hi,

I think that is the network latency problem. Let me know two things for checking it.

1. Ping latency
api-p.sendbird.com
api.sendbird.com

2. Your location

Thanks.

**Comment by karuppasamypandian0856** [comment]
hi,
i dont know how to get ping latency of you mentioned. but i got my log in device only 
**ERROR FOUND in connecting user (null)** 
What is the problem ?

**Comment by sf-jed-kyung** [comment]
1. I’d like to know the result of `ping api-p.sendbird.com` and `ping api.sendbird.com` commands in the terminal.

2. If the `error` is nil, it means there is no error. You should exchange two `NSLog` statements.

3. I think you opened `SendBird-iOS.xcodeproj` of the sample project. You have to open `SendBird-iOS.xcworkspace` because of `CocoaPods`.

**Comment by karuppasamypandian0856** [comment]
Thank you 
1)  ping latency
PING api-p.sendbird.com (52.77.161.98): 56 data bytes
64 bytes from 52.77.161.98: icmp_seq=0 ttl=49 time=208.841 ms
64 bytes from 52.77.161.98: icmp_seq=1 ttl=49 time=208.646 ms
64 bytes from 52.77.161.98: icmp_seq=2 ttl=49 time=208.581 ms
64 bytes from 52.77.161.98: icmp_seq=3 ttl=49 time=208.690 ms
64 bytes from 52.77.161.98: icmp_seq=4 ttl=49 time=208.666 ms
64 bytes from 52.77.161.98: icmp_seq=5 ttl=49 time=208.885 ms
64 bytes from 52.77.161.98: icmp_seq=6 ttl=49 time=208.684 ms
64 bytes from 52.77.161.98: icmp_seq=7 ttl=49 time=209.190 ms
64 bytes from 52.77.161.98: icmp_seq=8 ttl=49 time=208.943 ms
64 bytes from 52.77.161.98: icmp_seq=9 ttl=49 time=208.646 ms
64 bytes from 52.77.161.98: icmp_seq=10 ttl=49 time=208.700 ms
64 bytes from 52.77.161.98: icmp_seq=11 ttl=49 time=208.631 ms
64 bytes from 52.77.161.98: icmp_seq=12 ttl=49 time=208.710 ms
64 bytes from 52.77.161.98: icmp_seq=13 ttl=49 time=208.913 ms
64 bytes from 52.77.161.98: icmp_seq=14 ttl=49 time=208.472 ms
64 bytes from 52.77.161.98: icmp_seq=15 ttl=49 time=208.675 ms
64 bytes from 52.77.161.98: icmp_seq=16 ttl=49 time=208.574 ms
64 bytes from 52.77.161.98: icmp_seq=17 ttl=49 time=208.671 ms

PING api.sendbird.com (52.198.244.153): 56 data bytes
64 bytes from 52.198.244.153: icmp_seq=0 ttl=45 time=279.083 ms
64 bytes from 52.198.244.153: icmp_seq=1 ttl=45 time=278.756 ms
64 bytes from 52.198.244.153: icmp_seq=2 ttl=45 time=278.756 ms
64 bytes from 52.198.244.153: icmp_seq=3 ttl=45 time=278.843 ms
64 bytes from 52.198.244.153: icmp_seq=4 ttl=45 time=278.719 ms
64 bytes from 52.198.244.153: icmp_seq=5 ttl=45 time=278.725 ms
64 bytes from 52.198.244.153: icmp_seq=6 ttl=45 time=278.927 ms
64 bytes from 52.198.244.153: icmp_seq=7 ttl=45 time=278.731 ms
64 bytes from 52.198.244.153: icmp_seq=8 ttl=45 time=278.820 ms
64 bytes from 52.198.244.153: icmp_seq=9 ttl=45 time=278.718 ms
64 bytes from 52.198.244.153: icmp_seq=10 ttl=45 time=278.786 ms
64 bytes from 52.198.244.153: icmp_seq=11 ttl=45 time=278.784 ms
64 bytes from 52.198.244.153: icmp_seq=12 ttl=45 time=278.772 ms
64 bytes from 52.198.244.153: icmp_seq=13 ttl=45 time=278.780 ms
64 bytes from 52.198.244.153: icmp_seq=14 ttl=45 time=278.857 ms
64 bytes from 52.198.244.153: icmp_seq=15 ttl=45 time=278.745 ms
64 bytes from 52.198.244.153: icmp_seq=16 ttl=45 time=278.750 ms
64 bytes from 52.198.244.153: icmp_seq=17 ttl=45 time=278.736 ms
64 bytes from 52.198.244.153: icmp_seq=18 ttl=45 time=279.005 ms
64 bytes from 52.198.244.153: icmp_seq=19 ttl=45 time=278.742 ms
64 bytes from 52.198.244.153: icmp_seq=20 ttl=45 time=278.747 ms
64 bytes from 52.198.244.153: icmp_seq=21 ttl=45 time=279.002 ms
64 bytes from 52.198.244.153: icmp_seq=22 ttl=45 time=278.789 ms
64 bytes from 52.198.244.153: icmp_seq=23 ttl=45 time=278.729 ms
64 bytes from 52.198.244.153: icmp_seq=24 ttl=45 time=278.784 ms

**Comment by karuppasamypandian0856** [comment]
any update ?

**Comment by sf-jed-kyung** [comment]
The 208~279 ms latency is not so bad for SSL handshake. There were low latency issues from other customers at that time you mentioned. By the way, the issues were disappeared later. We thought that there seemed to be a network problem in the server region that we were using.  Did you see the `SSLHandshake failed` error again?

**Comment by karuppasamypandian0856** [comment]
not now

**Comment by karuppasamypandian0856** [comment]
From your sample project
Obj-c sample project cant run MGSwipeTableCell/MGSwipeTableCell.h not found with error
swift file run smoothly why ?

**Comment by sf-jed-kyung** [comment]
Have you ever tried running `pod update` in the sample project directory?

**Comment by karuppasamypandian0856** [comment]
yes, i'm new to pod file use, thank you.We need to update every time to run this?

**Comment by karuppasamypandian0856** [comment]
**checked about this issue: NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -981** 
 somebody told to check TransportSecurity in plist. Its already added in my case.

**Comment by karuppasamypandian0856** [comment]
Always this issue occurred when call setup function from Chatingview.m and pop from same.

**Comment by sf-jed-kyung** [comment]
1. You don’t have to run `pod update` always. When I update the sample project, I run `pod update` and include the new version of required frameworks. I have no idea why the `MGSwipeTableCell` framework is missed.
2. Could you tell me the lines where `dispach_sync()` is required? Thanks in advance.

**Comment by karuppasamypandian0856** [comment]
im not sure about it required or not `dispach_sync()`. i replaced that with setup function and return back from that viewcontroller.
```
[SBDGroupChannel createChannelWithName:… completionHandler:(….){
presentViewController which one use ChattingView.m view
we have declared presentViewController.view : ChattingView now its calling initWithCoder() that time crash occured

}];
- (id)initWithCoder:(NSCoder *)aDecoder {
    self = [super initWithCoder:aDecoder];
    if (self) {
        **[self setup];** 
    }
    return self;
}

- (void)setup {
                              [self.chattingTableView setContentInset:UIEdgeInsetsMake(0, 0, 10, 0)];
crash line-->        [self.messageTextView setTextContainerInset:UIEdgeInsetsMake(15.5, 0, 14, 0)];  
}
```

**Comment by karuppasamypandian0856** [comment]
okay i have changed the pushviewcontroller as separate function call with delay now works fine.
Any update from your side about this issue?

**Comment by karuppasamypandian0856** [comment]
That keyboard show/hide that inputView frame not changing when becomeFirstResponder/reignFirstResponder. Here reused your sample code chattingView.m

![screen shot 2017-02-21 at 9 59 19 am](https://cloud.githubusercontent.com/assets/19841870/23150805/7f5010b4-f81c-11e6-9a69-541dda12091b.png)

**Comment by sf-jed-kyung** [comment]
I think your modification is right. And `ChattingView.m` doesn’t include the feature to change the frame size when showing a keyboard. It has to be changed by a view controller that has `ChattingView`. Please refer to `GroupChannelViewController.m` or `OpenChannelViewController.m` in the sample.

https://github.com/smilefam/SendBird-iOS/blob/master/sample-objc/SendBird-iOS/GroupChannel/GroupChannelChattingViewController.m#L52-L60

https://github.com/smilefam/SendBird-iOS/blob/master/sample-objc/SendBird-iOS/GroupChannel/GroupChannelChattingViewController.m#L92-L110

**Comment by karuppasamypandian0856** [comment]
okay thank you
