### ISSUE TITLE
Is there a way to edit/update a specific message?

### ISSUE THREAD

**Issue by claudiumatei** [smilefam/sendbird-ios-framework#14]
Hi,

Is there a way to edit/update a specific message?

PS: deleting the message and adding a new one is not an option, since this is feasible only for the last message.

Thanks,
Claudiu

**Comment by sf-jed-kyung** [comment]
Hi,

Editing messages is a feature we have on our roadmap. We expect the feature will be released within the first half of this year. You will get a free upgrade when the feature will be released.

Thanks.
