### ISSUE TITLE
Delegate Issue protocol

### ISSUE THREAD

**Issue by swiftymarks** [smilefam/sendbird-ios-framework#15]
Hello I am having problem in the delegate protocol where I implement this on 2 view controllers
 SBDMain.add(self as SBDChannelDelegate, identifier: Constant.SENDBIRD_API_TOKEN)

Where this delegate only works on 1 View controller this issue occurs in v3.0.35
```
extension ChatListViewController: SBDChannelDelegate{
  func channel(_ sender: SBDBaseChannel, didReceive message: SBDBaseMessage) {
   // Some implementations
  }
}
```

```
extension ChatDetailsViewController: SBDChannelDelegate{
  func channel(_ sender: SBDBaseChannel, didReceive message: SBDBaseMessage) {
    if sender == groupChannel{
      // Some implementations
    }
  }
}
```

**Comment by sf-jed-kyung** [comment]
Hi, 

You have to add delegates for each view controller with different identifiers.

**Comment by swiftymarks** [comment]
Yes I did that. Will run some more few test. I'll get back to you Thanks!

**Comment by gorbat-o** [comment]
Hi, I have the same issue.
didReceive message delegate is never called
