### ISSUE TITLE
Every First time UserList Query return 0 !

### ISSUE THREAD

**Issue by karuppasamypandian0856** [smilefam/sendbird-ios-framework#18]
I have tried this below code for listing users but it does not return users every first time why.but second time its not happening?
```
    self.userListQuery = [SBDMain createAllUserListQuery];
    self.userListQuery.limit = 25;
    [self.userListQuery loadNextPageWithCompletionHandler:^(NSArray<SBDUser *> * _Nullable users, SBDError * _Nullable error) {
//User listing options.
}];

```

**Comment by sf-jed-kyung** [comment]
Was the `users` just empty without error?

**Comment by karuppasamypandian0856** [comment]
this error sometimes occur otherwise nil for every first time.

   ```
 [self.userListQuery loadNextPageWithCompletionHandler:^(NSArray<SBDUser *> * _Nullable users, SBDError * _Nullable error) {
        NSLog(@"USER count %lu ERROR list %@",(long)users.count,error.description);

 }];
        
//output
USER count 0 ERROR list Error Domain=Not valid Api-Token. Api-Token is missing. Code=400401 "(null)"
```

**Comment by karuppasamypandian0856** [comment]
[SendBird] Start getHostUrlWithCompletionhandler: 1489668428.186942
Time diff of routing: 2.186397
SendBird] Routing: https://api.sendbird.com : wss://ws.sendbird.com
SendBird] Start getHostUrlWithCompletionhandler: 1489668430.375037
SendBird] Finish getHostUrlWithCompletionhandler: 1489668430.375646
SendBird] URL: https://api.sendbird.comhttps://api.sendbird.com
SendBird] Finish getHostUrlWithCompletionhandler: 1489668430.434873
SendBird] URL: https://api.sendbird.com/v3/users?token=&limit=25
SendBird] Finish HTTP session: 1489668430.455478
SendBird] Finish HTTP session: 1489668433.881383
USER count 0 ERROR list Error Domain=Not valid Api-Token. Api-Token is missing. Code=400401

**Comment by sf-jed-kyung** [comment]
I think that you called [`loadNextPageWithCompletionHandler:`](https://docs.sendbird.com/ref/ios/Classes/SBDUserListQuery.html#//api/name/loadNextPageWithCompletionHandler:) of [`SBDUserListQuery `](https://docs.sendbird.com/ref/ios/Classes/SBDUserListQuery.html) before [`connectWithUserId:completionHandler:`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html#//api/name/connectWithUserId:completionHandler:) or [`connectWithUserId:accessToken:completionHandler:`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html#//api/name/connectWithUserId:accessToken:completionHandler:) of [`SBDMain`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html) was completed. Please check it. The connection is required for sending all requests to SendBird. If you already did it, run [`getConnectState`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html#//api/name/getConnectState) in the block that occurs the error.

**Comment by karuppasamypandian0856** [comment]
Thank you.Here i have checked about the Connection status by [SBDMain getConnectState] its return 0 or 3
    ```
        NSLog(@"SBD server Connection state %lu",(unsigned long)[SBDMain getConnectState]);

[SBDMain createUserListQueryWithUserIds:OperatorIDarray];
    [self.userListQuery loadNextPageWithCompletionHandler:^(*....) {
        NSLog(@"USER count %lu ERROR list %@",(long)users.count,error.description);
        NSLog(@"SBD server Connection state %lu",(unsigned long)[SBDMain getConnectState]);
}];
```
The output was 
SBD server Connection state 0
USER count 0 ERROR list Error Domain=Not valid Api-Token. Api-Token is missing. Code=400401 "(null)"
SBD server Connection state 1

**Comment by karuppasamypandian0856** [comment]
After that i have changed  all user list Query to particular users it gud.
`[SBDMain createAllUserListQuery];  --> [SBDMain createUserListQueryWithUserIds:OperatorIDarray];`

**Comment by karuppasamypandian0856** [comment]
loadPreviousMessagesFromTimestamp method is deprecated now.There is any other way to get this done for group channel.

  ```
  SBDMessageListQuery *messageQuery = [self.channel createMessageListQuery];
    [messageQuery loadPreviousMessagesFromTimestamp:EARLIEST_MESSAGE_TIMESTAMP limit:LIMIT reverse:REVERSE_ORDER completionHandler:^(NSArray<SBDBaseMessage *> * _Nullable messages, SBDError * _Nullable error) {
        if (error != nil) {
            NSLog(@"Error");
            return;
        }
    }];

```

**Comment by sf-jed-kyung** [comment]
1. The connection states are defined in [`SBDWebSocketConnectionState`](https://docs.sendbird.com/ref/ios/Constants/SBDWebSocketConnectionState.html) in `SBDTypes.h`. According to that, The `0` means that the connection is in progress and the `1` means that the connection is opened. The `3` represents that the connection is closed. If the connection state isn’t the `1`, every request returns the error.

2. `SBDMessageListQuery` class and the methods of it were deprecated in v3.0.28. Every method to get messages moved to [`SBDBaseChannel`](https://docs.sendbird.com/ref/ios/Classes/SBDBaseChannel.html) class because every message is included in a specific channel. You can find the methods to operate the same thing in the class. Use [`getPreviousMessagesByTimestamp:limit:reverse:messageType:customType:completionHandler:`](https://docs.sendbird.com/ref/ios/Classes/SBDMessageListQuery.html#//api/name/loadPreviousMessagesFromTimestamp:limit:reverse:completionHandler:) method in `SBDBaseChannel` instead of the [`loadPreviousMessagesFromTimestamp:limit:reverse:completionHandler:`](https://docs.sendbird.com/ref/ios/Classes/SBDMessageListQuery.html#//api/name/loadPreviousMessagesFromTimestamp:limit:reverse:completionHandler:) of `SBDMessageListQuery`.

**Comment by karuppasamypandian0856** [comment]
Thank you for information. i just followed your sample project so, i did not refer other method.

**Comment by karuppasamypandian0856** [comment]
okay if i get `SBDWebSocketConnecting` status from `[SBDMain getConnectState] `shall i wait to call UserlistQuery or reconnect a user?

how to reconnect user other than below method ?
```
[SBDMain connectWithUserId:USER_ID  completionHandler:^(...){
}]; 
```

**Comment by sf-jed-kyung** [comment]
If you already called [`connectWithUserId:completionHandler:`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html#//api/name/connectWithUserId:completionHandler:) of [`SBDMain`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html) and it was completed without error, just call [`reconnect`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html#//api/name/reconnect) of [`SBDMain`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html) to reconnect when you don’t get [`SBDWebSocketOpen`](https://docs.sendbird.com/ref/ios/Constants/SBDWebSocketConnectionState.html) state from [`getConnectState`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html#//api/name/getConnectState) of [`SBDMain`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html). SendBirdSDK has an automatic reconnection when the opened connection is closed by network problem. If you feel the delay for that, you can run the [`reconnect`](https://docs.sendbird.com/ref/ios/Classes/SBDMain.html#//api/name/reconnect) method to do that immediately. The method triggers the automatic reconnection, and the delegates of [`SBDConnectionDelegate`](https://docs.sendbird.com/ref/ios/Protocols/SBDConnectionDelegate.html) protocol are invoked according to the results.

**Comment by karuppasamypandian0856** [comment]
okay,thank you
