### ISSUE TITLE
getNextMessagesByTimestamp always return null

### ISSUE THREAD

**Issue by karuppasamypandian0856** [smilefam/sendbird-ios-framework#19]
i have tried getNextMessagesByTimestamp when channel has unread count but it always return null 
```
[self.channel getNextMessagesByTimestamp:MESSAGE_TIMESTAMP limit:self.channel.unreadMessageCount reverse:NO messageType:SBDMessageTypeFilterAll customType:nil completionHandler:^(NSArray<SBDBaseMessage *> * _Nullable messages, SBDError * _Nullable error){
        
            if (error != nil || !messages.count) {
                [commonmethod SBDReconnectUser];
                NSLog(@"getNextMessagesByTimestamp %@",error.description);
                return;
            }

}];
```

output:-
 [SendBird] Start getHostUrlWithCompletionhandler: 1490272609.560493
[SendBird] Finish getHostUrlWithCompletionhandler: 1490272609.560839
[SendBird] URL: https://api.sendbird.com/v3/group_channels/sendbird_group_channel_26422033_1f8f16640eb841bf84febc4056d0e4f83c552806/messages?next_limit=1&include=false&message_ts=1490272609456&reverse=false&prev_limit=0&is_sdk=true
[SendBird] Finish HTTP session: 1490272612.927837
SBD USER CONNECT STATUS 1
getNextMessagesByTimestamp (null)

**Comment by sf-jed-kyung** [comment]
I think that the `error` is nil and the `meesages.count` is zero in this case. It isn’t the error when the `messages.count` is zero. I recommend that the `!messages.count` is removed from the `if` clause.

How did you get `MESSAGE_TIMESTAMP`?

**Comment by karuppasamypandian0856** [comment]
Okay, but that time self.channel.unreadMessageCount has value. that `MESSAGE_TIMESTAMP` retrieved from Database. if DB has ) count we create timestamp by 
`[[NSDate date ] timeIntervalSince1970] * 1000.`

**Comment by sf-jed-kyung** [comment]
The way to create your `timestamp` isn’t wrong.  I'll ask you about two things.

1. Compare your `MESSAGE_TIMESTAMP` with `self.channel.lastMessage.createdAt` in that case. If the `MESSAGE_TIMESTAMP` is greater than `self.channel.lastMessage.createdAt`, then the `getNextMessagesByTimestamp:` method will return messages that is empty.
2. Check how to implement [`markAsRead`](https://docs.sendbird.com/ref/ios/Classes/SBDGroupChannel.html#//api/name/markAsRead) when your app receives a message.

**Comment by karuppasamypandian0856** [comment]
okay thank you.
