### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by BabyAzerty** [smilefam/sendbird-ios-framework#2]
Will you consider a Carthage support?

**Comment by sf-jed-kyung** [comment]
I'm sorry for the late answer and thank you for your interest in our framework. We don't have a plan to support Carthage officially yet. You can use Carthage to deploy this framework into your project if you want, but the framework will be installed in `Carthage/Checkouts` folder only. I think this won't be different from the direct download from git repo. We recommend to use Cocoapods.

**Comment by karuppasamypandian0856** [comment]
hi,
when try to install using carthage.i got this below error when run this cmd **carthage update --platform iOS**

> *** Cloning sendbird-ios-framework
> A shell task (/usr/bin/env git clone --bare --quiet https://github.com/smilefam/sendbird-ios-framework.git /Users/RifluxyssEL-C1/Library/Caches/org.carthage.CarthageKit/dependencies/sendbird-ios-framework) failed with exit code 128:
> error: RPC failed; result=56, HTTP code = 200
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed

**Comment by sf-jed-kyung** [comment]
We offer `Build` only via Carthage. I’ve never seen the error that you wrote. I’ll take a look at it.

**Comment by karuppasamypandian0856** [comment]
okay thank you.just asked for clarification.
