### ISSUE TITLE
v3.0.68 prevents upload to the appstore - causes "Invalid Bundle - Disallowed LLVM instrumentation"

### ISSUE THREAD

**Issue by urispmts** [smilefam/sendbird-ios-framework#22]
> Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

https://developer.apple.com/library/content/qa/qa1964/_index.html#//apple_ref/doc/uid/DTS40017675-CH1-SOURCECODE2

I'm using cocoapods to get it.

**running:** 
otool -l -arch all Pods/SendBirdSDK/SendBirdSDK.framework/SendBirdSDK | grep __llvm_prf

**results:**
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds

**Reverted back to 3.0.66 fixed the issue.**

Please fix.

**Comment by sf-jin-ku** [comment]
@urispmts We're updating the SDK version right now 3.0.69 should remove LLVM instrumentation things. It will be available within an hour.
