### ISSUE TITLE
How can i fix this overlapping of messages in iPhone5s?

### ISSUE THREAD

**Issue by krupa-detroja** [smilefam/sendbird-ios-framework#24]
![screen shot 2017-11-24 at 11 42 19 am](https://user-images.githubusercontent.com/30489948/33197642-ba6bacf2-d10c-11e7-95de-f17f6d6890ab.png)

**Comment by sf-jed-kyung** [comment]
Please refer to https://github.com/smilefam/SendBird-iOS/issues/27

Thanks.
