### ISSUE TITLE
Cannot Build to Simulator

### ISSUE THREAD

**Issue by zach-fuller** [smilefam/sendbird-ios-framework#26]
<img width="508" alt="screen shot 2018-01-15 at 11 20 46 am" src="https://user-images.githubusercontent.com/16906332/35060882-374f9ed4-fb85-11e7-93fc-ff3bd599017f.png">
Whenever I try to build to a simulator, I get a fatal error:

"lipo: -remove's specified would result in an empty fat file"

**Comment by sf-jed-kyung** [comment]
Did you install SendBirdSDK via CocoaPods?

**Comment by zach-fuller** [comment]
Yes I did, I've tried removing the pod and re-installing it with no luck. I also created a new project with the SendBirdkSDK as the only pod and ran into the same error

**Comment by sf-jed-kyung** [comment]
What is the version of CocoaPods that you are using?

**Comment by zach-fuller** [comment]
I had accidentally switched to the beta version of cocoapods, thanks for the quick response
