### ISSUE TITLE
Can't call SBDMain.getCurrentUser() 

### ISSUE THREAD

**Issue by MJRasmussen** [smilefam/sendbird-ios-framework#27]
Case:
I am trying to "pushViewController(self.groupChannelListViewController!, animated: false)" from my MainViewcontroller. But when i trying to get the channels "self.channels = Utils.loadGroupChannels()" then it fails on this line "let messageFileNamePrefix = Utils.sha256(string: String(format: "%@_channellist", (SBDMain.getCurrentUser()?.userId.urlencoding())!))! as NSString".

Seems like the problem happens when i haven't load my MainViewcontroller completely.

- Can i somehow check if im getting the user correctly?

**Comment by famous90** [comment]
Can you tell me what MainViewController are doing with Sendbird? If current user does not exist, it will occur some problems. I don't know exactly MainViewController, make sure SBDMain.connect get a SBDUser instance without error.

**Comment by MJRasmussen** [comment]
Thanks for the reply.

I am getting the SBDUser in my mainViewController, to make sure that i have the SDBUSer when i am connecting to Sendbird. (That's why i had complete the loading of my MainViewController)

- So the solution that i have come up with, was to make the button to the chatView inactive, until i have received the USDUser.
So i just close this issue for now.

**Comment by famous90** [comment]
Sounds good. Tell us whenever you have any questions. Thank you @MJRasmussen .
