### ISSUE TITLE
Error Domain=User not found. Code=400201 on createChannelWithUserIds method

### ISSUE THREAD

**Issue by kyivmobiledev** [smilefam/sendbird-ios-framework#28]
Now i am using SendBird 3.0 on my project.
when i call createChannelWithUserIds, i am getting error. "Error Domain=User not found. Code=400201"
please check this screen.
https://monosnap.com/file/IKlOOsWX7U6eq4IOntesTun4RFO9Y21

Looking forward to hear any reply.
Regards

**Comment by sf-jed-kyung** [comment]
Could you share your App ID and the user ID via [our technical support](https://help.sendbird.com/hc/en-us/requests/new?category=technical_support)?  Please don't post the App ID and the user ID here. 

Thank you.

**Comment by kyivmobiledev** [comment]
I just shared app id. can i get reply soon?

Thanks
