### ISSUE TITLE
Send file isn't calling completionHandler

### ISSUE THREAD

**Issue by tomcalmon** [smilefam/sendbird-ios-framework#29]
SDK Version: **v3.0.90**
iOS Version: **11.2.1**

Please, check what is happening with `sendFileMessage` methods, I had no `completionHandler` executed in any of them.

Thank you.

**Comment by famous90** [comment]
`completionHandler` is executed after the api(`sendFileMessage` or other apis can be) was executed. If you call sendFileMessage or other SendBird methods without `completionHandler`, just the logic that sends file message will be executed. Nothing more.

**Comment by tomcalmon** [comment]
Sorry, maybe I couldn't have explained well.

I put a breakpoint in `NSLog` into the `completionHandler` and It got executed on v3.0.89. Unfortunately, the same didnt happen in v3.0.90!

```
[channelSendBird sendFileMessageWithBinaryData: fileData
                                          filename: fileName
                                              type: fileType
                                              size: fileSize
                                              data: sendBirdData
                                        customType: customType
                                   progressHandler: ^(int64_t bytesSent, int64_t totalBytesSent, int64_t totalBytesExpectedToSend)
{
    
    // progress...
    
} completionHandler: ^(SBDFileMessage * _Nullable fileMessage, SBDError * _Nullable error) {
    
    NSLog(@"[SEND FILE ERROR] %@", error.localizedDescription);
	
    // Rest of completion code...
}];
```

**Comment by hyunsooo** [comment]
저도 마찬가지로 같은 에러가 발생합니다. 
v3.0.90으로 업데이트한 이후 파일메시지가 progressHandler 까지는 작동이 되지만 completionHandler에서 아무런 데이터가 오지 않습니다. error.localizedDescription도 로그가 찍히지 않습니다. 확인 부탁드립니다.

**Comment by famous90** [comment]
@tomcalmon @hyunsooo We apologize for the inconvenience. We found some issues about sending file message with a binary. We fixed and updated SDK just now. through updating SendBird SDK to 3.0.91, you can use the API smoothly. Sorry to bother you guys and thanks for reporting.

**Comment by tomcalmon** [comment]
@famous90 I'm glad you found the solution very fast. Thank you!
