### ISSUE TITLE
Compile errors after update to 3.0.103

### ISSUE THREAD

**Issue by nab0y4enko** [smilefam/sendbird-ios-framework#32]
![example xcworkspace 2018-06-29 18-24-11](https://user-images.githubusercontent.com/1070269/42100924-396e4fba-7bca-11e8-9e6c-4c5724a8e5d9.jpg)

**Comment by sf-jed-kyung** [comment]
Let me know how you installed and updated SendBird SDK.

**Comment by tomcalmon** [comment]
I am facing the same problem!
I've installed SendBird using CocoaPods.

**Comment by sf-jed-kyung** [comment]
Are you using Xcode 10 beta?

**Comment by tomcalmon** [comment]
No, i'm using **Version 9.2 (9C40b)**.

**Comment by sf-jed-kyung** [comment]
I fixed it in v3.0.104.

**Comment by nab0y4enko** [comment]
Thank you! I confirm, this is fixed.
