### ISSUE TITLE
Unable to upload app update with Xcode 10/iOS 12/swift 4.2 because of sendbird sdk

### ISSUE THREAD

**Issue by alf990** [smilefam/sendbird-ios-framework#36]
We use your sendbird Chat SDK for our application and it works very good, we like it. But there are problems since iOS 12 and Xcode 10. After updating our project we are not able to upload an new binary to the App Store with Xcode 10. The reason is that the apple throws an signing error because of the sendbird sdk. 
What can we do, to resolve this issue? 

<img width="768" alt="46680796-2185c200-cbea-11e8-8cac-d692f3d2ff69" src="https://user-images.githubusercontent.com/43998697/46747910-b6ec8900-ccb2-11e8-88ca-3653a2f81356.png">

**Comment by famous90** [comment]
hi, @alf990 Can you tell me how you integrated our SDK? Through Cocoa pod or Carthage?

**Comment by alf990** [comment]
hi @famous90 I use Carthage to integrate the sendbird sdk into my app. I also try run "carthage update" to ensure that I use the newest sendbird sdk.

**Comment by sf-jed-kyung** [comment]
Hi,

Please refer to the following solution for this issue:

https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

**Comment by alf990** [comment]
Hi Jed, 

Create an new run script phase like that:
 
<img width="990" alt="bildschirmfoto 2018-10-13 um 14 44 05" src="https://user-images.githubusercontent.com/43998697/46905718-edffac00-cef7-11e8-8f3e-16c6128da64f.png">

Helps fix this issue. Thanks a lot for the advice jed.
