### ISSUE TITLE
Error with code 15200

### ISSUE THREAD

**Issue by hash3r** [smilefam/sendbird-ios-framework#7]
Sometimes I received error from EventHandlerConnectBlock with code 15200.
I did not found error description with this code in docs.
Could you help me with this?

**Comment by sf-jed-kyung** [comment]
The error code `15200` is from `[SendBird markAllAsRead]`. We didn't know the error was missed out in [the docs](https://docs.sendbird.com/ios#misc). I have just updated it. Thanks.
