### ISSUE TITLE
Create channel is really slow when running on a device

### ISSUE THREAD

**Issue by marpal** [smilefam/sendbird-ios-framework#8]
We are running into an issue with createChannel when running on a device as it takes several seconds. When running in the simulator is works fine

**Comment by sf-jin-ku** [comment]
Hi @marpal

Could you send an email to support@sendbird.com?
Could you also add app_id , user_id and parameters you passed to the method?

Thanks!

**Comment by marpal** [comment]
@sf-jin-ku will do that
