### ISSUE TITLE
_NSStreamNetworkServiceTypeCallSignaling referenced from:       _SendBird_SRStreamNetworkServiceTypeFromURLRequest in SendBirdSDK(SendBird_SRURLUtilities.o)

### ISSUE THREAD

**Issue by inturbidus** [smilefam/sendbird-ios-framework#9]
<img width="704" alt="screen shot 2016-10-02 at 6 18 21 pm" src="https://cloud.githubusercontent.com/assets/905441/19024225/e2e4f2d0-88cc-11e6-953c-ef3afdd32f3f.png">

**Comment by inturbidus** [comment]
Cocoapods. I believe this is because that API is in iOS SDK 10, and I'm on 9.3 targeting 8.  

Also, SendBirdSDK targets 7, but warnings on compile say it's compiled for 8.

**Comment by sf-jed-kyung** [comment]
Do you use Xcode 7?

**Comment by sf-jed-kyung** [comment]
I'm trying to support Base SDK 9.3 in the next version.

**Comment by inturbidus** [comment]
Yes I use Xcode 7. 

–––––––––––––––––––––––––––––––––––––
Matt Hudson - Founder
–––––––––––––––––––––––––––––––––––––

Cell: (479) 313-6431
Website: www.voterockit.com
Email: matt.hudson@gmail.com
Twitter: @MattFWD

**Comment by sf-jed-kyung** [comment]
The SDK v3.0.13 was released in order to support Base SDK 9.3. Please check it.
